<?php

namespace Modules\Store\Database\Seeders;

use Illuminate\Database\Seeder;
use Modules\Store\Models\Banner;
use Carbon\Carbon;

class BannerSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $banners = [
            // Top Ads Banners
            [
                'name' => 'Cristor Gas Stove Promotion',
                'type' => 'hero',
                'position' => 'top-ads',
                'title' => 'SCG 40H AV',
                'subtitle' => '4 burner gas – Semi-flush design – High Efficiency burners for low consumption',
                'description' => 'Cast-iron pan supports with coordinated burner caps – AV electronic ignition and safety valves',
                'button_text' => 'Get It Now',
                'button_url' => '/products/cristor-gas-stove',
                'image_url' => 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=400&h=300&fit=crop',
                'background_start_color' => '#1e3a8a',
                'background_end_color' => '#3b82f6',
                'text_color' => '#ffffff',
                'settings' => [
                    'animation' => 'slide',
                    'duration' => 5000,
                    'auto_play' => true,
                    'show_indicators' => true,
                ],
                'is_active' => true,
                'sort_order' => 1,
                'start_date' => Carbon::now()->subDays(7),
                'end_date' => Carbon::now()->addDays(30),
                'target_audience' => ['all'],
                'impressions' => 1250,
                'clicks' => 89,
            ],
            [
                'name' => 'Condor Laptop Promotion',
                'type' => 'hero',
                'position' => 'top-ads',
                'title' => 'Laptop C Book',
                'subtitle' => 'CPU Intel Core i7-11700, 16M Cache, 4.80 GHz',
                'description' => 'NVIDIA GTX 3060 RAM DDR4 16Go/32Go - SSD 1TB + HDD 2TB',
                'button_text' => 'Shop Now',
                'button_url' => '/products/condor-laptop',
                'image_url' => 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=400&h=300&fit=crop',
                'background_start_color' => '#065f46',
                'background_end_color' => '#10b981',
                'text_color' => '#ffffff',
                'settings' => [
                    'animation' => 'fade',
                    'duration' => 5000,
                    'auto_play' => true,
                    'show_indicators' => true,
                ],
                'is_active' => true,
                'sort_order' => 2,
                'start_date' => Carbon::now()->subDays(5),
                'end_date' => Carbon::now()->addDays(25),
                'target_audience' => ['all'],
                'impressions' => 980,
                'clicks' => 67,
            ],
            [
                'name' => 'ACE Mobile Promotion',
                'type' => 'hero',
                'position' => 'top-ads',
                'title' => 'URBAN 2 HIT THE GROUND',
                'subtitle' => 'Snapdragon 8 Gen 2, Octa-core processor',
                'description' => 'Adreno 740 GPU, 8GB RAM - 128GB/256GB Storage, Expandable',
                'button_text' => 'Learn More',
                'button_url' => '/products/ace-mobile',
                'image_url' => 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=400&h=300&fit=crop',
                'background_start_color' => '#581c87',
                'background_end_color' => '#a855f7',
                'text_color' => '#ffffff',
                'settings' => [
                    'animation' => 'zoom',
                    'duration' => 5000,
                    'auto_play' => true,
                    'show_indicators' => true,
                ],
                'is_active' => true,
                'sort_order' => 3,
                'start_date' => Carbon::now()->subDays(3),
                'end_date' => Carbon::now()->addDays(20),
                'target_audience' => ['all'],
                'impressions' => 750,
                'clicks' => 45,
            ],

            // Phone Banner
            [
                'name' => 'Buzz Phone Banner',
                'type' => 'image',
                'position' => 'phone-banner',
                'title' => 'Buzz 3G Phone',
                'subtitle' => 'Experience the latest in mobile technology',
                'description' => 'High-performance smartphone with advanced features',
                'button_text' => 'Discover More',
                'button_url' => '/products/buzz-phone',
                'image_url' => 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=300&h=200&fit=crop',
                'background_start_color' => '#1f2937',
                'background_end_color' => '#374151',
                'text_color' => '#ffffff',
                'settings' => [
                    'animation' => 'fade',
                    'duration' => 3000,
                    'auto_play' => false,
                ],
                'is_active' => true,
                'sort_order' => 1,
                'start_date' => Carbon::now()->subDays(10),
                'end_date' => Carbon::now()->addDays(60),
                'target_audience' => ['all'],
                'impressions' => 2100,
                'clicks' => 156,
            ],

            // Hero Banners
            [
                'name' => 'Summer Sale Hero',
                'type' => 'hero',
                'position' => 'hero',
                'title' => 'Big Sale All In One',
                'subtitle' => 'Smart One',
                'description' => 'Get amazing discounts on all smart devices',
                'button_text' => 'Pre - Order Now',
                'button_url' => '/sale/summer',
                'image_url' => 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=600&h=300&fit=crop',
                'background_start_color' => '#1e3a8a',
                'background_end_color' => '#1e40af',
                'text_color' => '#ffffff',
                'settings' => [
                    'animation' => 'slide',
                    'duration' => 4000,
                    'auto_play' => true,
                    'show_indicators' => true,
                ],
                'is_active' => true,
                'sort_order' => 1,
                'start_date' => Carbon::now()->subDays(15),
                'end_date' => Carbon::now()->addDays(45),
                'target_audience' => ['all'],
                'impressions' => 3200,
                'clicks' => 234,
            ],
            [
                'name' => 'Kids Watch Promotion',
                'type' => 'hero',
                'position' => 'hero',
                'title' => 'Big Sale Kids Watch',
                'subtitle' => 'Wonderful Colour',
                'description' => 'Colorful and durable watches for kids',
                'button_text' => 'Pre - Order Now',
                'button_url' => '/products/kids-watch',
                'image_url' => 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&h=300&fit=crop',
                'background_start_color' => '#ea580c',
                'background_end_color' => '#f97316',
                'text_color' => '#ffffff',
                'settings' => [
                    'animation' => 'fade',
                    'duration' => 4000,
                    'auto_play' => true,
                    'show_indicators' => true,
                ],
                'is_active' => true,
                'sort_order' => 2,
                'start_date' => Carbon::now()->subDays(12),
                'end_date' => Carbon::now()->addDays(40),
                'target_audience' => ['all'],
                'impressions' => 2800,
                'clicks' => 189,
            ],

            // Product Deals
            [
                'name' => 'Plume L4 Deal',
                'type' => 'product-deal',
                'position' => 'product-deals',
                'title' => 'Plume L4',
                'subtitle' => 'High-performance air purifier',
                'description' => 'Advanced air purification technology for your home',
                'button_text' => 'Buy Now',
                'button_url' => '/products/plume-l4',
                'image_url' => 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=300&h=300&fit=crop',
                'background_start_color' => '#ffffff',
                'background_end_color' => '#f8fafc',
                'text_color' => '#1f2937',
                'settings' => [
                    'rating' => 4,
                    'price' => 20300.0,
                    'original_price' => 30405.0,
                    'discount' => 29,
                    'sold' => 75,
                    'available' => 25,
                    'timer' => [
                        'days' => 2,
                        'hrs' => 8,
                        'mins' => 45,
                        'secs' => 30
                    ],
                ],
                'is_active' => true,
                'sort_order' => 1,
                'start_date' => Carbon::now()->subDays(5),
                'end_date' => Carbon::now()->addDays(15),
                'target_audience' => ['all'],
                'impressions' => 890,
                'clicks' => 67,
            ],
            [
                'name' => 'NLAF Washing Machine Deal',
                'type' => 'product-deal',
                'position' => 'product-deals',
                'title' => 'NLAF-OD21N1G',
                'subtitle' => 'Smart washing machine',
                'description' => 'Energy-efficient washing machine with smart features',
                'button_text' => 'Shop Now',
                'button_url' => '/products/nlaf-washing-machine',
                'image_url' => 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=300&h=300&fit=crop',
                'background_start_color' => '#ffffff',
                'background_end_color' => '#f8fafc',
                'text_color' => '#1f2937',
                'settings' => [
                    'rating' => 4,
                    'price' => 27300.0,
                    'original_price' => null,
                    'discount' => null,
                    'sold' => 85,
                    'available' => 15,
                    'timer' => [
                        'days' => 3,
                        'hrs' => 12,
                        'mins' => 25,
                        'secs' => 15
                    ],
                ],
                'is_active' => true,
                'sort_order' => 2,
                'start_date' => Carbon::now()->subDays(3),
                'end_date' => Carbon::now()->addDays(12),
                'target_audience' => ['all'],
                'impressions' => 650,
                'clicks' => 43,
            ],

            // Condor Promotional Banners
            [
                'name' => 'Condor Kids Watch',
                'type' => 'sidebar',
                'position' => 'condor-promotional',
                'title' => 'Big Sale Kids Watch',
                'subtitle' => 'WONDERFUL CONDOR',
                'description' => 'Colorful and durable watches for children',
                'button_text' => 'Shop Now',
                'button_url' => '/products/condor-kids-watch',
                'image_url' => 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400&h=200&fit=crop',
                'background_start_color' => '#163366',
                'background_end_color' => '#001E50',
                'text_color' => '#ffffff',
                'settings' => [
                    'animation' => 'fade',
                    'duration' => 3000,
                    'auto_play' => false,
                ],
                'is_active' => true,
                'sort_order' => 1,
                'start_date' => Carbon::now()->subDays(8),
                'end_date' => Carbon::now()->addDays(35),
                'target_audience' => ['all'],
                'impressions' => 1200,
                'clicks' => 89,
            ],
            [
                'name' => 'Condor All In One',
                'type' => 'sidebar',
                'position' => 'condor-promotional',
                'title' => 'Big Sale All In One',
                'subtitle' => 'SMART LINE',
                'description' => 'Complete smart home solution',
                'button_text' => 'Shop Now',
                'button_url' => '/products/condor-all-in-one',
                'image_url' => 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=200&fit=crop',
                'background_start_color' => '#163366',
                'background_end_color' => '#001E50',
                'text_color' => '#ffffff',
                'settings' => [
                    'animation' => 'fade',
                    'duration' => 3000,
                    'auto_play' => false,
                ],
                'is_active' => true,
                'sort_order' => 2,
                'start_date' => Carbon::now()->subDays(6),
                'end_date' => Carbon::now()->addDays(30),
                'target_audience' => ['all'],
                'impressions' => 980,
                'clicks' => 67,
            ],

            // ACE Promotional Banners
            [
                'name' => 'ACE Clever 3',
                'type' => 'sidebar',
                'position' => 'ace-promotional',
                'title' => 'Big Sale CLEVER 3',
                'subtitle' => 'SMART LINE',
                'description' => 'Advanced smart device with cutting-edge technology',
                'button_text' => 'Shop Now',
                'button_url' => '/products/ace-clever-3',
                'image_url' => 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=400&h=200&fit=crop',
                'background_start_color' => '#000428',
                'background_end_color' => '#004e92',
                'text_color' => '#ffffff',
                'settings' => [
                    'animation' => 'fade',
                    'duration' => 3000,
                    'auto_play' => false,
                ],
                'is_active' => true,
                'sort_order' => 1,
                'start_date' => Carbon::now()->subDays(7),
                'end_date' => Carbon::now()->addDays(32),
                'target_audience' => ['all'],
                'impressions' => 1100,
                'clicks' => 78,
            ],
            [
                'name' => 'ACE Urban 5',
                'type' => 'sidebar',
                'position' => 'ace-promotional',
                'title' => 'Big Sale URBAN 5',
                'subtitle' => 'SMART LINE',
                'description' => 'Urban lifestyle smart device',
                'button_text' => 'Shop Now',
                'button_url' => '/products/ace-urban-5',
                'image_url' => 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=400&h=200&fit=crop',
                'background_start_color' => '#000428',
                'background_end_color' => '#004e92',
                'text_color' => '#ffffff',
                'settings' => [
                    'animation' => 'fade',
                    'duration' => 3000,
                    'auto_play' => false,
                ],
                'is_active' => true,
                'sort_order' => 2,
                'start_date' => Carbon::now()->subDays(5),
                'end_date' => Carbon::now()->addDays(28),
                'target_audience' => ['all'],
                'impressions' => 950,
                'clicks' => 62,
            ],

            // Sidebar Banners
            [
                'name' => 'Sidebar Promotion 1',
                'type' => 'sidebar',
                'position' => 'sidebar',
                'title' => 'Special Offer',
                'subtitle' => 'Limited Time',
                'description' => 'Get 20% off on selected items',
                'button_text' => 'Learn More',
                'button_url' => '/offers/special',
                'image_url' => 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=300&h=200&fit=crop',
                'background_start_color' => '#ec4899',
                'background_end_color' => '#f472b6',
                'text_color' => '#ffffff',
                'settings' => [
                    'animation' => 'fade',
                    'duration' => 2000,
                    'auto_play' => false,
                ],
                'is_active' => true,
                'sort_order' => 1,
                'start_date' => Carbon::now()->subDays(10),
                'end_date' => Carbon::now()->addDays(50),
                'target_audience' => ['all'],
                'impressions' => 800,
                'clicks' => 45,
            ],

            // Bottom Banners
            [
                'name' => 'Bottom Promotion 1',
                'type' => 'hero',
                'position' => 'bottom',
                'title' => 'Newsletter Signup',
                'subtitle' => 'Stay Updated',
                'description' => 'Get the latest offers and product updates',
                'button_text' => 'Subscribe',
                'button_url' => '/newsletter/signup',
                'image_url' => 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&h=200&fit=crop',
                'background_start_color' => '#1f2937',
                'background_end_color' => '#374151',
                'text_color' => '#ffffff',
                'settings' => [
                    'animation' => 'slide',
                    'duration' => 3000,
                    'auto_play' => true,
                    'show_indicators' => false,
                ],
                'is_active' => true,
                'sort_order' => 1,
                'start_date' => Carbon::now()->subDays(20),
                'end_date' => Carbon::now()->addDays(100),
                'target_audience' => ['all'],
                'impressions' => 1500,
                'clicks' => 120,
            ],
        ];

        foreach ($banners as $bannerData) {
            Banner::create($bannerData);
        }

        $this->command->info('Banner seeder completed successfully!');
        $this->command->info('Created ' . count($banners) . ' banners for different positions and types.');
    }
}
